In [1]:
import numpy as np
import pandas as pd 

In [2]:
from sklearn.datasets import make_blobs
X,y = make_blobs(n_samples=500,#total number of points equally divided among clusters
                  centers=2, #number of centers
                  n_features=2, #The number of features for each sample.
                  shuffle=True,#Shuffle the samples
                  random_state=40,#Determines random number generation for dataset creation. Pass an intfor reproducible output across multiple function calls.
                  cluster_std=1.0 #The standard deviation of the clusters.
                 )

In [3]:
X

array([[ -1.30337776,  -8.9771589 ],
       [ -1.9286514 ,  -7.63458522],
       [  3.75108134,  -4.82018524],
       [  5.40515136,  -4.10999262],
       [  5.62385901,  -3.48874087],
       [  6.58475353,  -4.48493711],
       [ -1.62162558,  -8.57535964],
       [ -2.95329499,  -8.48222611],
       [ -1.81488248,  -8.3369102 ],
       [ -1.91081622,  -9.02894249],
       [  7.16711931,  -5.126769  ],
       [  6.80928959,  -4.16283942],
       [  5.90902804,  -4.31361291],
       [ -1.8610918 ,  -7.40170196],
       [ -1.77692952,  -9.25880303],
       [  5.85899532,  -5.77471727],
       [  3.27352261,  -3.26658651],
       [  7.00785027,  -3.44110254],
       [ -1.25797779,  -8.00743496],
       [  8.74520733,  -4.18370241],
       [ -0.97193427,  -7.17316019],
       [  6.18906208,  -4.10334804],
       [  5.14475054,  -4.39049508],
       [ -1.26286104,  -7.92305758],
       [ -1.55276528,  -8.78372889],
       [ -1.13599245,  -7.83714475],
       [ -2.04526856, -10.16766281],
 

In [4]:
X.shape

(500, 2)

In [5]:
y

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,

In [6]:
y.shape

(500,)

In [7]:
#change o to -1
y=np.where(y<=0,-1,1)
y

array([-1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1, -1, -1,  1,  1,
        1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1,
        1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,
        1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1,  1,
        1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,
        1, -1,  1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,
        1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
        1,  1,  1, -1,  1,  1, -1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,
        1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,
       -1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,
       -1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1,  1,  1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,
        1,  1,  1,  1, -1

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,)

In [9]:
class SVM:
    def __init__(self,lr=0.001,lambda_param=0.01,n_iters=100):
        self.lr=lr
        self.lambda_param = lambda_param
        self.n_iters = n_iters
        self.weights = None
        self.bias = None 
    
    def fit(self,X,y):
        m,n = X.shape
        
        self.weights = np.zeros(n)
        
        self.bias = 0
        
        for _ in range(self.n_iters):
            for idx,x_i in enumerate(X):
                
                #f_i = np.dot(x_i,self.weights)-self.bias
                condition = y[idx] * (np.dot(x_i, self.weights) - self.bias) >= 1
                
                if condition:
                    self.weights -= self.lr* ( 2 * self.lambda_param * self.weights)
                else:
                    self.weights -= self.lr*( 2 * self.lambda_param * self.weights - np.dot(x_i,y[idx]))
                    self.bias -= y[idx]
                
                              
    def predict(self,X):
        return np.sign(np.dot(X,self.weights)-self.bias)

In [10]:
svm =SVM()
svm.fit(X_train,y_train)

In [11]:
y_pred = svm.predict(X_test)
y_pred

array([-1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,
       -1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,
       -1., -1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,
       -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,
       -1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,
       -1.,  1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1.,
        1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1.,
       -1., -1., -1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,
        1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,  1., -1.,
       -1., -1.,  1., -1., -1.,  1., -1., -1.])

In [12]:
y_test 

array([-1,  1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1,
       -1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1,
        1, -1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,
        1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  1, -1,
        1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,
       -1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1, -1,  1, -1, -1,
        1, -1,  1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1,
        1, -1, -1,  1, -1, -1])

In [13]:
def accuracy(y,y_pred):
    return np.sum(y==y_pred)/len(y)   

acc = accuracy(y_test, y_pred)
acc

1.0